### ISSUE TITLE
VMWare login

### ISSUE THREAD

**Issue by marceloamoretti** [javiercrowsoft/CrowSoft-Cairo#10]
Hello, I have installed the VMWare software and the disk image. But I need your password to login and test the program. Is it possible?

**Comment by javiercrowsoft** [comment]
Hi Marcelo, the password is 14FeDyAr. Log with user Javier Alvarez. Open a terminal and type:
```
$ scd
```
Open another terminal and type:
```
$ cd ~
$ prax start
```
Then open Chrome and navigate to:
```
cairodigital.dev
```
To login into the system just click the link in the right corner of the top bar.
The user is
```
administrador@crowsoft.com.ar
```
Password
```
Coco123456789
```
Click on company: 
```
Crow Market
```
